# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build PDF & ePub
formats: [htmlzip, pdf]
 
# Set the version of Python and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
sphinx:
  builder: html,dirhtml,singlehtml
  configuration: conf.py
  fail_on_warning: true
  
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: true

python:
  install:
  - requirements: docs/requirements.txt
